travis:
  secure:
    BINSTAR_TOKEN: NU0Wv6fW+7T4KCQU6lxTucDKJqDirnof9WgGp5HBgBDUjmCEfHxHCltsGZ72y4Off11YcdjGpLPk9Rgeiac8uSbDLzBsph32+vz3wy8xR6olF0ojJhIB9ex0BT0My31lQP7rBse9vU5VQY4PnbwBXx3Z2JO7tT/3HyjT/tjJwjctx7wCIVm5ZJV38YqHtK5rreRjYiiUfWZwAHUQ7EjqkohW/IUly0CF8Opm5VEG6V60q4o4yGBG7vNThbhJUE2EZy+F//xmVqurDmm2zvBzChFNAM6lnK95Mzf1VPwyk1i9Dnm67Yacon+lD2lClo06QIDH8g3YHFswM+wSv5fGiC5joENtr1yhADUgg08cokByEeoGSaySxOkZRw3zIgTaacJIU+LUmEUr23HPjuTZxS7/sxCxZjESNaNBuSSoDBbIeZVQL480UQFjoGqnODfcRTBdV+qs6LOpD0QVYvfOVEdsFG3I3acyZlAHTDRIxwR2OMrRrscNk07/uCFmZvoH+UQ+YMAhhWvOIbAW8dW3/BtqO+8rd8pGbx0j2q9mLJOhVlj2afPr/a2WMXhBjuIe/lliVGTdFQlnXUofGON+zibkxujYVzHDXPphkW4Hoq1SkQDf+WZWLFdNUnwRJORw/Ynzn0LmQILwf6z4FChjD+ZxKQ5ns1PaYgE5+ZfEjuo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
